### ISSUE TITLE
[v7 RC] "public function get_software_link" is missing for the game Urban Terror

### ISSUE THREAD

**Issue by UG-Asger** [tltneon/lgsl#210]
Would recommend to add UrT Launcher connect link as below in class.php. The launcher is official FS software.

"urbanterror"   => "urt://{IP}:{S_PORT}",

**Comment by tltneon** [comment]
Done

**Comment by UG-Asger** [comment]
Hey there.

You missed this in protocol.php ;)
![image](https://github.com/user-attachments/assets/3ff25e00-8871-4118-8fd5-6633b77d72be)

**Comment by UG-Asger** [comment]
Hey there ;)

Apparantly this wasn't enough :(
![image](https://github.com/user-attachments/assets/c927af10-588e-4625-b305-8f9ffd998a0a)
